var express=require('express')
routes=express.Router()
var workController=require('../controller/work-controller')
routes.post('/addworks',workController.addWorks)
routes.post('/viewworkbyworkerid',workController.viewWorkByWorkerId)
routes.post('/viewworkbycustomer',workController.viewWorkByCustomer)
routes.post('/listallarchitect',workController.listAllArchitects)
routes.post('/listallinterior',workController.listAllInterior)
routes.post('/listallelectrician',workController.listAllElectrician)
routes.post('/viewworkbyid',workController.viewWorkId)
routes.post('/viewarchitect',workController.ViewArchitect)
routes.post('/viewinterior',workController.viewInterior)
routes.post('/viewelectrician',workController.viewElectrician)
routes.post('/deletework',workController.deleteWork)
module.exports = routes